spring:
  application:
    name: storeops-api
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    com.storeops: INFO
